name: Build and Deploy

on:
  push:
    branches:
      - main  # ajustez en fonction de la branche sur laquelle vous voulez déclencher le déploiement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build site
      run: |
        pelican -s publishconf.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # ajustez en fonction du dossier de sortie de votre site Pelican
